### ISSUE TITLE
can't open localhost:8080

### ISSUE THREAD

**Issue by deepakkumar138** [OpenNetworkingFoundation/CENTENNIAL#11]
I am not able to open localhost:8080. It shows connection timeout. I opened ./karaf installed necessary features but still its not opening. Can anyone help me with this?

**Comment by HighstreetHerbert** [comment]
OpenDaylight DLUX GUI is running on port 8181. After starting karaf (./bin/karaf and installing all features) you can open the DLUX GUI with "http://localhost:8181/index.html". Please try this URL. It should open the login screen of OpenDaylight DLUX.

**Comment by olinchy** [comment]
Try localhost:8181

**Comment by demx8as6** [comment]
Hi Liu,

 

Is there any problem?

 

Cheers,

Martin

 

Von: olinchy [mailto:notifications@github.com] 
Gesendet: Donnerstag, 27. Oktober 2016 11:44
An: OpenNetworkingFoundation/CENTENNIAL <CENTENNIAL@noreply.github.com>
Betreff: Re: [OpenNetworkingFoundation/CENTENNIAL] can't open localhost:8080 (#11)

 

Try localhost:8181

**Comment by olinchy** [comment]
no problem at all
