### ISSUE TITLE
code-Oxygen-SR3    "Mounted Resources" shows all mounted points as undefined

### ISSUE THREAD

**Issue by haiyunhzhang** [OpenNetworkingFoundation/CENTENNIAL#22]
1. Following the guideline to add simulation devices 
https://github.com/OpenNetworkingFoundation/CENTENNIAL/tree/master/code-Oxygen-SR3
Name: Sim2230
 IP Address: 127.0.0.1
 port: 2230
 Username: admin
 Password: admin
 Required: check

2. Browse /apidoc/explorer/index.html# for entries,

"Mounted Resources" shows all mounted points as undefined.
undefined
--
undefined
undefined
undefined

Regards,

Harry

**Comment by demx8as6** [comment]
https://github.com/OpenNetworkingFoundation/CENTENNIAL/commit/7f6c36c0fa5fade91147228c721d33e70b8caeaa

[INFO] ONF :: Wireless :: help-bundle ..................... SUCCESS [  1.471 s]
[INFO] ONF :: Wireless :: mwtnFeatures .................... SUCCESS [  6.160 s]
[INFO] ONF :: Wireless :: mwtn-parent ..................... SUCCESS [  7.081 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:16 min
[INFO] Finished at: 2019-04-19T16:32:50+02:00
[INFO] ------------------------------------------------------------------------
demx8as6@devmartin:~/workspace/onf/CENTENNIAL/code-Carbon-SR1$

**Comment by demx8as6** [comment]
Sorry - was wrong issue - reopened.

**Comment by demx8as6** [comment]
Please use ODL fluorine.
https://wiki.onap.org/pages/viewpage.action?pageId=63996073
and later: http://172.17.0.2:8181/apidoc/explorer/index.html
