### ISSUE TITLE
Release code-Carbon-SR1 Build Failed

### ISSUE THREAD

**Issue by haiyunhzhang** [OpenNetworkingFoundation/CENTENNIAL#23]
I have followed the steps to setup the environment and cloned the projects. the "mvn install failed because of  "devicemanager-impl: Error(s) found in bundle configuration ". The details are copied,

~/odl/CENTENNIAL/code-Carbon-SR1$ mvn clean install -DskipTests
.............

[INFO] ONF :: Wireless :: mwtn-parent ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:50 min
[INFO] Finished at: 2019-04-18T16:06:11+00:00
[INFO] Final Memory: 206M/848M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.felix:maven-bundle-plugin:3.0.1:bundle (default-bundle) on project devicemanager-impl: Error(s) found in bundle configuration -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :devicemanager-impl

Thanks,

Harry

**Comment by demx8as6** [comment]
fix in https://github.com/OpenNetworkingFoundation/CENTENNIAL/commit/7f6c36c0fa5fade91147228c721d33e70b8caeaa

[INFO] ONF :: Wireless :: help-bundle ..................... SUCCESS [  1.471 s]
[INFO] ONF :: Wireless :: mwtnFeatures .................... SUCCESS [  6.160 s]
[INFO] ONF :: Wireless :: mwtn-parent ..................... SUCCESS [  7.081 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:16 min
[INFO] Finished at: 2019-04-19T16:32:50+02:00
[INFO] ------------------------------------------------------------------------
demx8as6@devmartin:~/workspace/onf/CENTENNIAL/code-Carbon-SR1$
