### ISSUE TITLE
ode-Oxygen-SR3 Build Failed --- Non-resolvable parent POM 

### ISSUE THREAD

**Issue by haiyunhzhang** [OpenNetworkingFoundation/CENTENNIAL#24]
~/odl/CENTENNIAL/code-Oxygen-SR3$ mvn clean install -DskipTests

[FATAL] Non-resolvable parent POM for com.highstreet.technologies.odlux:odlux-app-minimumApp:[unknown-version]: Failure to find com.highstreet.technologies.odlux:odlux-parent:pom:0.7.3-SNAPSHOT in https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of opendaylight-snapshot has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 6, column 10
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 36, column 12
 @
[ERROR] The build could not read 6 projects -> [Help 1]
[ERROR]
[ERROR]   The project com.highstreet.technologies.odlux:odlux-app-apiDemo:[unknown-version] (/home/ubuntu/odl/CENTENNIAL/code-Oxygen-SR3/apps/odlux/apps/apiDemo/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.highstreet.technologies.odlux:odlux-app-apiDemo:[unknown-version]: Could not find artifact com.highstreet.technologies.odlux:odlux-parent:pom:0.7.3-SNAPSHOT in opendaylight-snapshot (https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/) and 'parent.relativePath' points at no local POM @ line 6, column 10 -> [Help 2]
[ERROR]
[ERROR]   The project com.highstreet.technologies.odlux:odlux-app-connectApp:[unknown-version] (/home/ubuntu/odl/CENTENNIAL/code-Oxygen-SR3/apps/odlux/apps/connectApp/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.highstreet.technologies.odlux:odlux-app-connectApp:[unknown-version]: Failure to find com.highstreet.technologies.odlux:odlux-parent:pom:0.7.3-SNAPSHOT in https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of opendaylight-snapshot has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 6, column 10 -> [Help 2]
[ERROR]
[ERROR]   The project com.highstreet.technologies.odlux:odlux-app-demoApp:[unknown-version] (/home/ubuntu/odl/CENTENNIAL/code-Oxygen-SR3/apps/odlux/apps/demoApp/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.highstreet.technologies.odlux:odlux-app-demoApp:[unknown-version]: Failure to find com.highstreet.technologies.odlux:odlux-parent:pom:0.7.3-SNAPSHOT in https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of opendaylight-snapshot has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 6, column 10 -> [Help 2]
[ERROR]
[ERROR]   The project com.highstreet.technologies.odlux:odlux-app-faultApp:[unknown-version] (/home/ubuntu/odl/CENTENNIAL/code-Oxygen-SR3/apps/odlux/apps/faultApp/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.highstreet.technologies.odlux:odlux-app-faultApp:[unknown-version]: Failure to find com.highstreet.technologies.odlux:odlux-parent:pom:0.7.3-SNAPSHOT in https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of opendaylight-snapshot has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 6, column 10 -> [Help 2]
[ERROR]
[ERROR]   The project com.highstreet.technologies.odlux:odlux-app-inventoryApp:[unknown-version] (/home/ubuntu/odl/CENTENNIAL/code-Oxygen-SR3/apps/odlux/apps/inventoryApp/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.highstreet.technologies.odlux:odlux-app-inventoryApp:[unknown-version]: Failure to find com.highstreet.technologies.odlux:odlux-parent:pom:0.7.3-SNAPSHOT in https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of opendaylight-snapshot has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 6, column 10 -> [Help 2]
[ERROR]
[ERROR]   The project com.highstreet.technologies.odlux:odlux-app-minimumApp:[unknown-version] (/home/ubuntu/odl/CENTENNIAL/code-Oxygen-SR3/apps/odlux/apps/minimumApp/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.highstreet.technologies.odlux:odlux-app-minimumApp:[unknown-version]: Failure to find com.highstreet.technologies.odlux:odlux-parent:pom:0.7.3-SNAPSHOT in https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of opendaylight-snapshot has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 6, column 10 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by demx8as6** [comment]
fix in https://github.com/OpenNetworkingFoundation/CENTENNIAL/commit/7f6c36c0fa5fade91147228c721d33e70b8caeaa


[INFO] ONF :: Wireless :: help-bundle ..................... SUCCESS [  0.929 s]
[INFO] ONF :: Wireless :: mwtnFeatures .................... SUCCESS [  2.194 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:34 min
[INFO] Finished at: 2019-04-19T16:21:40+02:00
[INFO] ------------------------------------------------------------------------
demx8as6@devmartin:~/workspace/onf/CENTENNIAL/code-Oxygen-SR3$
